// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.15.0
// source: meeting.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteMeetingRecordsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomIDs []string `protobuf:"bytes,1,rep,name=roomIDs,proto3" json:"roomIDs,omitempty"`
}

func (x *DeleteMeetingRecordsReq) Reset() {
	*x = DeleteMeetingRecordsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meeting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMeetingRecordsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeetingRecordsReq) ProtoMessage() {}

func (x *DeleteMeetingRecordsReq) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeetingRecordsReq.ProtoReflect.Descriptor instead.
func (*DeleteMeetingRecordsReq) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteMeetingRecordsReq) GetRoomIDs() []string {
	if x != nil {
		return x.RoomIDs
	}
	return nil
}

type DeleteMeetingRecordsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteMeetingRecordsResp) Reset() {
	*x = DeleteMeetingRecordsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meeting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMeetingRecordsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeetingRecordsResp) ProtoMessage() {}

func (x *DeleteMeetingRecordsResp) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeetingRecordsResp.ProtoReflect.Descriptor instead.
func (*DeleteMeetingRecordsResp) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{1}
}

var File_meeting_proto protoreflect.FileDescriptor

var file_meeting_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x72, 0x74, 0x63, 0x22, 0x33, 0x0a, 0x17,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x73, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x32, 0x75, 0x0a,
	0x0e, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x63, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x24, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e,
	0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meeting_proto_rawDescOnce sync.Once
	file_meeting_proto_rawDescData = file_meeting_proto_rawDesc
)

func file_meeting_proto_rawDescGZIP() []byte {
	file_meeting_proto_rawDescOnce.Do(func() {
		file_meeting_proto_rawDescData = protoimpl.X.CompressGZIP(file_meeting_proto_rawDescData)
	})
	return file_meeting_proto_rawDescData
}

var file_meeting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meeting_proto_goTypes = []interface{}{
	(*DeleteMeetingRecordsReq)(nil),  // 0: Meeting.rtc.DeleteMeetingRecordsReq
	(*DeleteMeetingRecordsResp)(nil), // 1: Meeting.rtc.DeleteMeetingRecordsResp
}
var file_meeting_proto_depIdxs = []int32{
	0, // 0: Meeting.rtc.MeetingService.DeleteMeetingRecords:input_type -> Meeting.rtc.DeleteMeetingRecordsReq
	1, // 1: Meeting.rtc.MeetingService.DeleteMeetingRecords:output_type -> Meeting.rtc.DeleteMeetingRecordsResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meeting_proto_init() }
func file_meeting_proto_init() {
	if File_meeting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meeting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMeetingRecordsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meeting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMeetingRecordsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meeting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meeting_proto_goTypes,
		DependencyIndexes: file_meeting_proto_depIdxs,
		MessageInfos:      file_meeting_proto_msgTypes,
	}.Build()
	File_meeting_proto = out.File
	file_meeting_proto_rawDesc = nil
	file_meeting_proto_goTypes = nil
	file_meeting_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MeetingServiceClient is the client API for MeetingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MeetingServiceClient interface {
	DeleteMeetingRecords(ctx context.Context, in *DeleteMeetingRecordsReq, opts ...grpc.CallOption) (*DeleteMeetingRecordsResp, error)
}

type meetingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeetingServiceClient(cc grpc.ClientConnInterface) MeetingServiceClient {
	return &meetingServiceClient{cc}
}

func (c *meetingServiceClient) DeleteMeetingRecords(ctx context.Context, in *DeleteMeetingRecordsReq, opts ...grpc.CallOption) (*DeleteMeetingRecordsResp, error) {
	out := new(DeleteMeetingRecordsResp)
	err := c.cc.Invoke(ctx, "/Meeting.rtc.MeetingService/DeleteMeetingRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeetingServiceServer is the server API for MeetingService service.
type MeetingServiceServer interface {
	DeleteMeetingRecords(context.Context, *DeleteMeetingRecordsReq) (*DeleteMeetingRecordsResp, error)
}

// UnimplementedMeetingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMeetingServiceServer struct {
}

func (*UnimplementedMeetingServiceServer) DeleteMeetingRecords(context.Context, *DeleteMeetingRecordsReq) (*DeleteMeetingRecordsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMeetingRecords not implemented")
}

func RegisterMeetingServiceServer(s *grpc.Server, srv MeetingServiceServer) {
	s.RegisterService(&_MeetingService_serviceDesc, srv)
}

func _MeetingService_DeleteMeetingRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMeetingRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeetingServiceServer).DeleteMeetingRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Meeting.rtc.MeetingService/DeleteMeetingRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeetingServiceServer).DeleteMeetingRecords(ctx, req.(*DeleteMeetingRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MeetingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Meeting.rtc.MeetingService",
	HandlerType: (*MeetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteMeetingRecords",
			Handler:    _MeetingService_DeleteMeetingRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meeting.proto",
}
