
rpc:
  name: Rtc
  port:
    - 11300

rtc:
  url:
    - ws://192.168.3.10:7880
  innerURL: ws://127.0.0.1:7880 # Internal Address
  apiKey: "API9a68KZ52QTmX"
  apiSecret: "ZlzM0gxLj1TqUXje2tnGGxSpiFrozDzHep0LGpfBY4cB"

log:
  storageLocation: ./logs/
  rotationTime: 24
  remainRotationCount: 2
  remainLogLevel: 6
  isStdout: false
  isJson: false
  withStack: false

etcd:
  address: [ 127.0.0.1:2379 ]
  username:
  password:
  ttl: 5
  lease: 10
  timeout: 5


mongo:
  uri: ''
  # List of MongoDB server addresses.
  # Used for constructing the MongoDB URI if 'uri' above is empty.
  # For a standalone setup, specify the address of the single server.
  # For a sharded cluster, specify the addresses of the Mongos servers.
  # Example: [ '127.0.0.1:37017', '172.28.0.2:37017' ]
  # Default MongoDB database name
  # Maximum connection pool size
  address: [ 127.0.0.1:27017 ]
  database: meeting_v1
  username:
  password:
  maxPoolSize: 100

redis:
  address: [ 127.0.0.1:6379 ]
  username: ''
  password: openIM123